### ISSUE TITLE
Error when use tensorflow2

### ISSUE THREAD

**Issue by wushanyun64** [jeherr/element-encoder#1]
Hi
There's an error raised when running this code with tensorflow2:
`module 'tensorflow' has no attribute 'placeholder'`

Maybe use:
```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 
```
instead of:
`import tensorflow as tf` would be better.

**Comment by jeherr** [comment]
This code was developed before Tensorflow 2 was released in a stable version, and is primarily here to accompany the published work it was used for. I will update the README to specify that information, but probably won't be making updates to this code to maintain it for future versions of dependencies. You're absolutely free to fork it, make it your own, and update it however you want though.
